### ISSUE TITLE
branch: base off astroidmail/astroid:master

### ISSUE THREAD

**Issue by gauteh** [c-alpha/astroid#10]
It would be easier to test if you `reset --hard` your `master` to astroidmail/astroid:master and `rebase -i` `cmake` off that one (dropping the unrelated commits).

**Comment by c-alpha** [comment]
Ok, I have added astroidmail/astroid as a new upstream to my repo, and did the `reset --hard` of my master to astroidmail/astroid:master.

Not quite sure what you're trying to achieve with the `rebase -i cmake` though? I would have done a
```
git checkout cmake
git merge master
```
to replay all changes from master since the split onto cmake, so that any PR from my cmake branch would only show the CMake-related changes in the diff.

If I e.g. discarded all meson related changes from master in the `rebase -i`, these would show up as deletions in a PR from cmake. Not sure if that would make merging easier for you?

**Comment by gauteh** [comment]
The meson commits have now been merged to master so that part isn't correct anymore. 

It is similar, but it prepares the cmake branch for being merged into master at a later point, keeping the history clean without any merge commits. I would have to do that in the end, but if it is done regularly it is easier. In this case none of the files exist from before so it probably wont make much difference.

**Comment by c-alpha** [comment]
I see. So on `rebase -i`, I'll drop all commits from master so that the commits in the cmake branch concern CMake stuff only.

**Comment by gauteh** [comment]
Yes, so that the new tip of that branch is as if you started afresh from 
the tip of master.

I recommend making a backup-branch of `cmake` before you start in case 
something goes wrong with merging/conflicting stuff.

Normally, rebasing is frowned upon, but it is essentially the same as 
sending a new version of a patch set. So I think it is convenient to do 
for pull-requests and minor/non-conflicting features.

**Comment by c-alpha** [comment]
There was too much stuff to manually merge. I ended up recreating a fresh cmake branch. This made merging your PR #12 a bit harder, but that's probably what I asked for.;-)

**Comment by gauteh** [comment]
I tested out your :cmake branch;

* I've updated astroidmail:master to use upper-case @PREFIX@ and 
  @GIT_DESC@ in src/build_config.hh.in. However, when I do:

```
$ mkdir build.cmake
$ cd build.cmake
$ cmake -GNinja ../
$ ninja
```
  
build_config.hh cannot be found. The generated file is located in 
`build.cmake/src/build_config.hh` which seems to not be included in 
the -I flags. Perhaps you have an old build_config.hh leftover from 
SCons?

```
1/53] Building CXX object CMakeFiles/astroid.dir/src/astroid.cc.o
FAILED: CMakeFiles/astroid.dir/src/astroid.cc.o
/usr/bin/c++  -DBOOST_LOG_DYN_LINK -DDEBUG -DDISABLE_EMBEDDED -DDISABLE_PLUGINS -DSASSCTX_
CONTEXT_H -I../src -I../src/actions -I../src/modes -I../src/modes/editor -I../src/modes/th
read_index -I../src/modes/thread_view -I../src/plugin -I../src/utils -I../src/utils/gmime
-std=c++14   -pthread -I/usr/include/gtkmm-3.0 -I/usr/lib/gtkmm-3.0/include -I/usr/include
/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/gdkmm-3.0
/include -I/usr/include/giomm-2.4 -I/usr/lib/giomm-2.4/include -I/usr/include/pangomm-1.4
-I/usr/lib/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/
usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/includ
e/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -
I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/cairo
mm-1.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I
/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/s
igc++-2.0 -I/usr/lib/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -D_LARGEFILE64_SOURC
E -I/usr/include/gmime-3.0 -I/usr/include/webkitgtk-3.0 -I/usr/include/libsoup-2.4 -I/usr/
include/libxml2 -I/usr/include/vte-2.91 -I/usr/include/p11-kit-1 -Wall -g -Wextra -MD -MT
CMakeFiles/astroid.dir/src/astroid.cc.o -MF CMakeFiles/astroid.dir/src/astroid.cc.o.d -o C
MakeFiles/astroid.dir/src/astroid.cc.o -c ../src/astroid.cc
../src/astroid.cc:29:11: fatal error: build_config.hh: No such file or directory
 # include "build_config.hh"
           ^~~~~~~~~~~~~~~~~
```


* I rebased off master, dropping the MacOS commits that were part of an 
  old PR you sent. These shouldn't be part of the new cmake-branch, 
  otherwise you're essentially asking me to merge them again. Removed by 
  dropping the lines when rebasing off `astroidmail:master`.

* Merge commits removed when rebasing.

The end result, with a clean git history, can be found in: `gauteh:cmake-dev`.

(if you want to reset your branch to that tip do (carefully) `git reset --hard 
gauteh:cmake-dev`)

**Comment by c-alpha** [comment]
On 2017-10-17, at 10:23 , Gaute Hope <notifications@github.com> wrote:

> [...]
> (if you want to reset your branch to that tip do (carefully) `git reset --hard 
> gauteh:cmake-dev`)
> [...]

Done.
