### ISSUE TITLE
build_config.hh is not generated in ../src/ but in build folder and therefore not found

### ISSUE THREAD

**Issue by gauteh** [c-alpha/astroid#13]
When generating `build_config.hh` it is placed in the build directory. However, it does not seem that the build directory is included in the search path (`-I`), so it is not found. Note that it used to be placed in the `../src/` by SCons previously and may be left-over since it is not tracked by git.

```
[1/53] Building CXX object CMakeFiles/astroid.dir/src/astroid.cc.o
FAILED: CMakeFiles/astroid.dir/src/astroid.cc.o
/usr/bin/c++  -DBOOST_LOG_DYN_LINK -DDEBUG -DDISABLE_PLUGINS -DHAVE_NOTMUCH_INDEX_FILE -DSASSCTX_CONTEXT_H -I../src -I../src/actions -I../src/modes -I../src/modes/editor -I../src/modes/thread_index -I../src/modes/thread_view -I../src/plugin -I../src/utils -I../src/utils/gmime -std=c++14   -pthread -I/usr/include/gtkmm-3.0 -I/usr/lib/gtkmm-3.0/include -I/usr/include/atkmm-1.6 -I/usr/include/gtk-3.0/unix-print -I/usr/include/gdkmm-3.0 -I/usr/lib/gdkmm-3.0/include -I/usr/include/giomm-2.4 -I/usr/lib/giomm-2.4/include -I/usr/include/pangomm-1.4 -I/usr/lib/pangomm-1.4/include -I/usr/include/glibmm-2.4 -I/usr/lib/glibmm-2.4/include -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairomm-1.0 -I/usr/lib/cairomm-1.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/sigc++-2.0/include -I/usr/include/gdk-pixbuf-2.0 -D_LARGEFILE64_SOURCE -I/usr/include/gmime-3.0 -I/usr/include/webkitgtk-3.0 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/vte-2.91 -I/usr/include/p11-kit-1 -Wall -g -Wextra -MD -MT CMakeFiles/astroid.dir/src/astroid.cc.o -MF CMakeFiles/astroid.dir/src/astroid.cc.o.d -o CMakeFiles/astroid.dir/src/astroid.cc.o -c ../src/astroid.cc
../src/astroid.cc:29:11: fatal error: build_config.hh: No such file or directory
 # include "build_config.hh"
           ^~~~~~~~~~~~~~~~~
compilation terminated.
[6/53] Building CXX object CMakeFiles/astroid.dir/src/config.cc.o
ninja: build stopped: subcommand failed.
```

**Comment by c-alpha** [comment]
Strangely enough, this works for me.
How do you invoke `cmake` and `make`, `ninja`, ...?
I tested your PR #17 and it works ok on my system; just to be sure we're fixing the problem and not just concealing a symptom.

_On a loosely related note:_ should we have a front-end script that does the `mkdir build` etc.? Personally I would be in favour of having one. This would be for the rest of us, while experts can still call `cmake`, `ninja`, etc. by hand as they want.

**Comment by gauteh** [comment]
```
mkdir build
cd build
cmake -GNinja ..
ninja
```

You probably have an old build_config.hh leftover from SCons in your srcroot/src. There should only be a ..hh.in file there.

**Comment by gauteh** [comment]
Maybe something like this could work: https://cmake.org/cmake/help/v3.0/command/build_command.html

Would be good with a one-line command, but a CMake solution would be the best.

**Comment by gauteh** [comment]
hm.. not sure if that works as I thought, maybe the --build flag.

**Comment by gauteh** [comment]
You can do:

```
$ cmake -Bbuild -H. -GNinja
$ cmake --build build
```

That's two lines like in most other build-systems.

**Comment by c-alpha** [comment]
> Note that it used to be placed in the ../src/ by SCons previously and may be left-over since it is not tracked by git.

Bummer! I had indeed overlooked to delete it. Ashes to my head...

I won't merge your PR #17 btw., since I put the include directory in a slightly different location. **But thanks for the hint!**

**Comment by gauteh** [comment]
c-alpha writes on november 4, 2017 14:46:
> I won't merge your PR #17 btw., since I put the include directory in a slightly different location. **But thanks for the hint!**
> 

Sounds good!
