### ISSUE TITLE
make a pull-request to the main repo

### ISSUE THREAD

**Issue by gauteh** [c-alpha/astroid#16]
It would be nice at this point if you make a pull-request from your branch to the main repo so that people can start testing out. Then I can refer to that PR when I tell people to bug you about finishing the branch ;)

**Comment by mxmehl** [comment]
Yeah, that would be great indeed. Thanks for the work, @c-alpha!

**Comment by c-alpha** [comment]
On 2017-11-03, at 11:01 , Gaute Hope <notifications@github.com> wrote:

> It would be nice at this point if you make a pull-request from your branch to the main repo so that people can start testing out.

Now I see. I knew "to root sth." as a shorthand for "pulling sth. (out) by the root", i.e. to remove it without a trace. But that's apparently not what you intended...

> Then I can refer to that PR when I tell people to bug you about finishing the branch ;)
> [...]

Ok, I guess I have been volunteered. ;-)) For which thanks, and I'll be happy to fulfil my role.

@gauteh and @mxmehl, thanks for the endorsement!

PR coming...

**Comment by c-alpha** [comment]
@gauteh, should I submit the PR against master, or do you want to create a cmake branch on the master repo first?

**Comment by gauteh** [comment]
c-alpha writes on november 3, 2017 22:47:
> @gauteh, should I submit the PR against master, or do you want to create a cmake branch on the master repo first?
> 

Hm, think we can use your branch for now with a PR against master. Then 
I can submit any changes to you. You can mention in the PR that any 
issues should be reported on your repo like you've done now.

**Comment by c-alpha** [comment]
Done. PR astroidmail/astroid#428

**Comment by gauteh** [comment]
Great! Thanks, by the way: Don't remove Meson or SCons yet. We can decide later how to keep them, so for now please omit that commit from the PR.

**Comment by gauteh** [comment]
in gauteh:cmake-dev I separated out the SCons.. stuff from your commits and rebased with master.

**Comment by c-alpha** [comment]
> Great! Thanks, by the way: Don't remove Meson or SCons yet. We can decide later how to keep them, so for now please omit that commit from the PR.

I have reverted commit c-alpha/astroid@2fd82f54e088a1fbd8f7b2e82e4b165ebe2d6b6f, and brought back `SConstruct`.

**Comment by gauteh** [comment]
c-alpha writes on november 4, 2017 17:42:
>> Great! Thanks, by the way: Don't remove Meson or SCons yet. We can decide later how to keep them, so for now please omit that commit from the PR.
> 
> I have reverted commit c-alpha/astroid@2fd82f54e088a1fbd8f7b2e82e4b165ebe2d6b6f, and brought back `SConstruct`.
> 

thanks, but you have to drop the commit from the series (not revert) 
and re-write the one commit (like I did in gauteh:cmake-dev). Otherwise the 
PR won't merge without conflicts since there has been made changes to 
the meson files in the mean time on master. There shouldn't be any back 
and forth in the series when it is merged into master. As it is now I 
can't check out your branch and rebase it off master to test it with all 
the other improvements that have been made on the master branch.

**Comment by c-alpha** [comment]
> [...]
> thanks, but you have to drop the commit from the series (not revert) 
> and re-write the one commit (like I did in gauteh:cmake-dev). Otherwise the 
> PR won't merge without conflicts since there has been made changes to 
> the meson files in the mean time on master. There shouldn't be any back 
> and forth in the series when it is merged into master. As it is now I 
> can't check out your branch and rebase it off master to test it with all 
> the other improvements that have been made on the master branch.
> [...]

I'm not the biggest git wizard in the known universe. All how-tos on the Interwebs I have been resorting to so far answered to "how to delete/modify a commit I already pushed?" with "don't unless you want to loose some friends."

I guess I'd be looking at things along the lines of these?

Delete an already pushed commit:

Case 2 of http://christoph.ruegg.name/blog/git-howto-revert-a-commit-already-pushed-to-a-remote-reposit.html

Fix an earlier commit:

https://github.com/blog/2019-how-to-undo-almost-anything-with-git#user-content-fix-an-earlier-commit

**Comment by gauteh** [comment]
c-alpha writes on november 4, 2017 23:24:
>> [...]
>> thanks, but you have to drop the commit from the series (not revert) 
>> and re-write the one commit (like I did in gauteh:cmake-dev). Otherwise the 
>> PR won't merge without conflicts since there has been made changes to 
>> the meson files in the mean time on master. There shouldn't be any back 
>> and forth in the series when it is merged into master. As it is now I 
>> can't check out your branch and rebase it off master to test it with all 
>> the other improvements that have been made on the master branch.
>> [...]
> 
> I'm not the biggest git wizard in the known universe. All how-tos on the Interwebs I have been resorting to so far answered to "how to delete/modify a commit I already pushed?" with "don't unless you want to loose some friends."
> 
> I guess I'd be looking at things along the lines of these?
> 
> Delete an already pushed commit:
> 
> Case 2 of http://christoph.ruegg.name/blog/git-howto-revert-a-commit-already-pushed-to-a-remote-reposit.html
> 
> Fix an earlier commit:
> 
> https://github.com/blog/2019-how-to-undo-almost-anything-with-git#user-content-fix-an-earlier-commit
> 

Yeah - it's kind of a no-no for more or less stable branches; so I 
should not do it for the master branch. But, since this is a feature 
branch (and not that big, like webkit2js), it is better to clean it up 
rather than including all the trials and errors, and their reverts. 
Otherwise, this redundant history will go into the main repository and 
it will be harder to later undo a commit. Say I want to revert the CMake 
branch, and in one of the commits an unrelated file was modified, then I 
would undo that change aswell without necessary noticing. Also, since I 
modified the meson build system while you were working on this (where 
the meson file was deleted) the merge would have conflicting changes 
since I then modfied a file on master after you deleted it in the cmake 
branch - the cmake branch would therefore have to essentially be 
re-written on merge anyway to solve the conflicts. The flip side is that 
I have to pull --force when I want to get your latest changes. What I 
did on cmake-dev was:

git checkout -b cmake-dev c-alpha/cmake
git rebase -i master # make sure master is up-to-date with astroidmail/master
# drop the scons commit about removing remianding files
# edit the commit that did mostly something else, but also deleted the
#   SConstruct: fe45642.

The rebase now stops *after* this commit, so I do a soft reset above 
that:

git reset HEAD^
git checkout master -- SConstruct # fetch the file from master (since 
# restoring this file to master version undoes the change I want to omit)
# maybe have to do git add now
git commit --amend 
git rebase --continue

Should now be good to go. Check with a diff against c-alpha/cmake to see 
if something bad happened.

Hope that makes everything more confusing.

Cheers, Gaute

**Comment by gauteh** [comment]
Thanks a lot for all the effort!! I've merge the PR into master.
