### ISSUE TITLE
missing internal editor build

### ISSUE THREAD

**Issue by c-alpha** [c-alpha/astroid#5]
See https://github.com/astroidmail/astroid/blob/master/SConstruct

**Comment by gauteh** [comment]
This one is only a matter of an extra -D flag (optionally).

**Comment by c-alpha** [comment]
@gauteh, it would seem that I could additionally exclude the following files from compilation?
```
src/modes/editor/editor.cc
src/modes/editor/external.cc
src/modes/editor/plugin.cc
```

**Comment by gauteh** [comment]
c-alpha writes on oktober 18, 2017 11:54:
> @gauteh, it would seem that I could additionally exclude the following files from compilation?
> ```
> src/modes/editor/editor.cc
> src/modes/editor/external.cc
> src/modes/editor/plugin.cc
> ```

Maybe, probably not editor.cc.

**Comment by gauteh** [comment]
Nice, just to clarify; gtkmm/socket.h is not related to webkitgtk but the X server that GTK is running on.

**Comment by c-alpha** [comment]
Thanks for clarifying. At least the conclusion (must not build on macOS) remains valid. Phew! ;-)

  --alex

-- 
www.condition-alpha.com / @c_alpha
