### ISSUE TITLE
compile_commands.json ?

### ISSUE THREAD

**Issue by gauteh** [c-alpha/astroid#8]
Does CMake create the compile_commands.json ? Does it if you use ninja as backend?

**Comment by c-alpha** [comment]
I don't have ninja installed, so can't tell.

CMake docs say:

> # Ninja
> Generates build.ninja files.
> 
> A build.ninja file is generated into the build tree. Recent versions of the ninja program can build the project through the “all” target. An “install” target is also provided.
> 
> For each subdirectory sub/dir of the project, additional targets are generated:
> 
> `sub/dir/all`
> Depends on all targets required by the subdirectory.
> `sub/dir/install`
> Runs the install step in the subdirectory, if any.
> `sub/dir/test`
> Runs the test step in the subdirectory, if any.
> `sub/dir/package`
> Runs the package step in the subdirectory, if any.
> 
> ## Fortran Support
> The Ninja generator conditionally supports Fortran when the ninja tool has the required features. As of this version of CMake the needed features have not been integrated into upstream Ninja. Kitware maintains a branch of Ninja with the required features on github.com/Kitware/ninja.

**Comment by c-alpha** [comment]
https://clang.llvm.org/docs/JSONCompilationDatabase.html
> Currently CMake (since 2.8.5) supports generation of compilation databases for Unix Makefile builds (Ninja builds in the works) with the option `CMAKE_EXPORT_COMPILE_COMMANDS`.

As CMake is at 3.10 currently, it seems the short answer is "yes". The medium-long answer appears to be that you may need to call CMake as `cmake -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ...`.

**Comment by gauteh** [comment]
c-alpha writes on oktober 16, 2017 23:44:
> https://clang.llvm.org/docs/JSONCompilationDatabase.html
>> Currently CMake (since 2.8.5) supports generation of compilation databases for Unix Makefile builds (Ninja builds in the works) with the option `CMAKE_EXPORT_COMPILE_COMMANDS`.
> 
> As CMake is at 3.10 currently, it seems the short answer is "yes". The medium-long answer appears to be that you may need to call CMake as `cmake -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ...`.
> 

Ok, that's good!
